/**
 * A unique identifier for all entities, ensuring type safety.
 */
export type ULID = string;

/**
 * Represents a single tag that can be applied to a Thought.
 */
export interface Tag {
  readonly id: ULID;
  readonly name: string;
  readonly color: string;
}

/**
 * Represents a key-value attribute with a defined type, attached to a Segment.
 */
export interface Attribute {
  readonly id: ULID;
  readonly fieldName: string;
  readonly fieldValue: string;
  readonly fieldType: 'text' | 'number' | 'date' | 'boolean';
}

/**
 * A Segment is a nested piece of content within a Thought, representing a
 * single, atomic idea or piece of information.
 */
export interface Segment {
  readonly id: ULID;
  readonly thoughtId: ULID;
  readonly title: string | null;
  readonly content: string;
  readonly attributes: readonly Attribute[];
  readonly createdAt: Date;
  readonly updatedAt: Date;
}

/**
 * A Thought is the central entity in LogoMesh. It represents a single,
 * containerized concept or "thought bubble". For the AgentX competition,
 * a Thought will contain a software requirement.
 */
export interface Thought {
  readonly id: ULID;
  readonly title: string;
  readonly description: string | null;
  readonly tags: readonly Tag[];
  readonly segments: readonly Segment[];
  readonly createdAt: Date;
  readonly updatedAt: Date;
}

/**
 * Represents the structured report generated by our Green Agent after
 * evaluating a Purple Agent's submission.
 */
export interface EvaluationReport {
  readonly rationaleDebt: {
    readonly score: number; // 0.0 to 1.0
    readonly details: string;
  };
  readonly architecturalCoherenceDebt: {
    readonly score: number; // 0.0 to 1.0
    readonly details: string;
  };
  readonly testingVerificationDebt: {
    readonly score: number; // 0.0 to 1.0
    readonly details: string;
  };
}

/**
 * Represents a single evaluation run within the AgentX competition context.
 */
export interface Evaluation {
  readonly id: ULID;
  readonly status: 'running' | 'complete' | 'error';
  readonly contextualDebtScore: number | null; // Overall score
  readonly report: EvaluationReport | null;
  readonly createdAt: Date;
  readonly completedAt: Date | null;
}
