/**
 * A unique identifier for all entities, ensuring type safety.
 */
export type ULID = string;

/**
 * Represents a single tag that can be applied to a Thought.
 */
export interface Tag {
  readonly id: ULID;
  readonly name: string;
  readonly color: string;
}

/**
 * Represents a key-value attribute with a defined type, attached to a Segment.
 */
export interface Attribute {
  readonly id: ULID;
  readonly fieldName: string;
  readonly fieldValue: string;
  readonly fieldType: 'text' | 'number' | 'date' | 'boolean';
}

/**
 * A Segment is a nested piece of content within a Thought, representing a
 * single, atomic idea or piece of information.
 */
export interface Segment {
  readonly id: ULID;
  readonly thoughtId: ULID;
  readonly title: string | null;
  readonly content: string;
  readonly attributes: readonly Attribute[];
  readonly createdAt: Date;
  readonly updatedAt: Date;
}

/**
 * A Thought is the central entity in LogoMesh. It represents a single,
 * containerized concept or "thought bubble". For the AgentX competition,
 * a Thought will contain a software requirement.
 */
export interface Thought {
  readonly id: ULID;
  readonly title: string;
  readonly description: string | null;
  readonly tags: readonly Tag[];
  readonly segments: readonly Segment[];
  readonly createdAt: Date;
  readonly updatedAt: Date;
}

/**
 * Represents the structured report generated by our Green Agent after
 * evaluating a Purple Agent's submission.
 */

/**
 * Represents a piece of information (context) the agent used in a reasoning step.
 */
export interface ContextItem {
  readonly id: ULID;
  readonly source: 'memory' | 'tool' | 'user';
  readonly content: string;
}

/**
 * Represents a single step in the agent's multi-step reasoning process.
 * This is the raw data that will be fed into the analysis services.
 */
export interface ReasoningStep {
  readonly stepIndex: number;
  readonly goal: string;
  readonly consumedContext: readonly ContextItem[];
  readonly rationale: string;
  readonly action: {
    readonly toolName: string;
    readonly toolInput: any;
  };
  readonly actionResult: any;
}

/**
 * Represents a single instance of contextual debt being incurred at a specific step.
 */
export interface DebtEvent {
  readonly stepIndex: number;
  readonly incurredByContextId: ULID; // Which piece of bad context caused this?
  readonly debtScore: number; // How much debt was incurred in this step (0.0 to 1.0)
  readonly details: string; // LLM explanation of why it was a mistake.
}

/**
 * The new, detailed report for Rationale Debt, including a step-by-step trace.
 */
export interface RationaleDebtReport {
  readonly overallScore: number; // The final, aggregated score.
  readonly trace: readonly DebtEvent[]; // The step-by-step breakdown of where debt was incurred.
}

/**
 * The detailed report for Architectural Debt, including raw complexity metrics.
 */
export interface ArchitecturalDebtReport {
  readonly score: number; // The final, composite score from 0.0 (high debt) to 1.0 (low debt).
  readonly details: string; // A human-readable summary of the findings.
  readonly metrics: any | null; // The raw, detailed metrics from the escomplex library. Null if analysis fails.
}

export interface EvaluationReport {
  readonly rationaleDebt: RationaleDebtReport;
  readonly architecturalCoherenceDebt: ArchitecturalDebtReport;
  readonly testingVerificationDebt: {
    readonly score: number; // 0.0 to 1.0
    readonly details: string;
  };
}

/**
 * Represents a single evaluation run within the AgentX competition context.
 */
export interface Evaluation {
  readonly id: ULID;
  readonly status: 'running' | 'complete' | 'error';
  readonly contextualDebtScore: number | null; // Overall score
  readonly report: EvaluationReport | null;
  readonly createdAt: Date;
  readonly completedAt: Date | null;
}
