/**
 * Represents the core entities of the application.
 * These interfaces define the shape of the data that is used throughout the application.
 */

export interface Thought {
  id: string;
  title: string;
  description?: string | null;
  created_at: string;
  updated_at: string;
  color?: string | null;
  position?: { x: number; y: number };
  fields?: Record<string, unknown>;
  metadata?: Record<string, unknown>;
  tags?: Tag[];
  segments?: Segment[];
}

export interface Segment {
  segment_id: string;
  thought_bubble_id: string;
  title?: string | null;
  content: string;
  content_type?: string; // e.g., 'text', 'code', 'mermaid'
  fields?: Record<string, unknown>;
  metadata?: Record<string, unknown>;
  created_at: string;
  updated_at: string;
  abstraction_level?: string;
  local_priority?: number;
  cluster_id?: string;
  sort_order?: number;
}

export interface Tag {
  /**
   * The unique identifier for the tag.
   * This is optional because it is generated by the database when a new tag is created.
   */
  tag_id?: string;
  name: string;
  color?: string;
  created_at?: string;
}

export interface Edge {
  edge_id: string;
  source_thought_id: string;
  target_thought_id: string;
  label?: string;
  created_at: string;
  updated_at: string;
  // any other relevant fields
}

export interface UserSettings {
  user_id: string;
  settings: Record<string, unknown>;
  // any other relevant fields
}

export interface GraphState {
  // Define structure for graph state if needed
  zoom_level?: number;
  viewport_position?: { x: number; y: number };
}

export interface NodePosition {
  node_id: string;
  x: number;
  y: number;
}
